### ISSUE TITLE
No source found

### ISSUE THREAD

**Issue by mohitleo9** [razum2um/clj-debugger#11]
Hey,
I am trying to use this plugin but every time I use it I get No source found error.
Here is how I am using it : 
(require 'debugger.core)
(defn some-func [](range 5)) 
(debugger.core/break (some-func))

> No source found
> (source some-func)
> (defn some-func [](range 5)) 
> Could you please help me with it.

**Comment by razum2um** [comment]
@mohitleo9 debugger uses `clojure.repl/source` to get the code, but currently it cannot get the source of the function defined in the repl

```
user=> (defn some-func [x] x)
#'user/some-func
user=> (clojure.repl/source some-func)
Source not found
nil
```

Besides features like return control value are working right in the repl.
You also can insert it into your's source files.

It's an upstream problem and I advise you to file a ticket in the clj's jira

**Comment by mohitleo9** [comment]
Thanks a lot.
