### ISSUE TITLE
Support Clojure 1.5

### ISSUE THREAD

**Issue by bbatsov** [razum2um/clj-debugger#4]
Clojure 1.5 is still widely used, so it'd be great if `clj-debugger` supported it (most projects target 1.5+ these days).

**Comment by Bruce-Connor** [comment]
I've forked the repo and changed all `some?` to `some`. AFAIC that's all that's necessary.

To test I started the repl using clojure 1.5, manually loaded each of the source files, and didn't get any sort of error or complain. 
Does that mean I eliminated all 1.6 dependencies?

**Comment by Bruce-Connor** [comment]
Ignore my previous comment, I was delirious.

**Comment by Malabarba** [comment]
Ok, I've replaced all instances of `some?` with `(not (nil x))`, how can test if that is all that's necessary?

**Comment by bbatsov** [comment]
Just run the debugger locally with 1.5.

**Comment by Malabarba** [comment]
Ok. If that's all then this should be fine.
